import type { Metadata } from "next";
import { Providers } from "../providers";
import "../globals.css";
import { poppins } from "@/lib/global.fonts";

export const metadata: Metadata = {
  title: "Galleries",
  description: "Generated by create next app",
  icons: '/logo.png'
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <div >
        <Providers>{children}</Providers>
    </div>
  )
}